trigger: none

pool:
  vmImage: windows-latest

variables:
  gitVersion: '5.3.7'
  
stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    pool:
      vmImage: windows-latest
    steps:
      - pwsh: >
          Set-Content -Path GitVersion.yml -Value `
            "mode: Mainline",
            "next-version: 1.0",
            "branches:",
            "  master:",
            "    regex: ^master$|^main$",
            "  feature:",
            "    regex: ^feature?[/-]",
            "    tag: ci-{BranchName}",
            "  pull-request:",
            "    tag: pr"
        displayName: GitVersion - Write GitVersion.yml

      - task: gitversion/setup@0
        displayName: Install GitVersion Tool
        inputs:
          versionSpec: $(gitVersion)

      - task: gitversion/execute@0
        displayName: Run GitVersion
        inputs:
          useConfigFile: true
          configFilePath: GitVersion.yml
          
      - task: DotNetCoreCLI@2
        inputs:
          command: "restore"
          projects: |
            **/*.csproj
          feedsToUse: "select"
          includeNuGetOrg: true
        displayName: Dotnet Restore

      - task: DotNetCoreCLI@2
        inputs:
          command: "test"
          projects: |
            **/*.csproj
        displayName: Build

      - task: DotNetCoreCLI@2
        inputs:
          command: "pack"
          versioningScheme: byEnvVar
          versionEnvVar: GitVersion.NuGetVersion
          packDestination: $(Build.ArtifactStagingDirectory)/package
          arguments: "-o $(Build.ArtifactStagingDirectory)/package"
          projects: |
            **/*.csproj
        displayName: Package 
        
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
        displayName: Publish Build Artifacts        

- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    condition: 
        or(
           in(variables['Build.SourceBranch'], 'refs/heads/main'), 
           in(variables['Build.Reason'], 'Manual')
        )  
    pool:
      vmImage: windows-latest 
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: 'Download artifacts'
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'drop'
          itemPattern: 
          downloadPath: '$(System.ArtifactsDirectory)'   
      - task: NuGetCommand@2
        displayName: Publish package to nuget.org using ASOS organisation account
        inputs:
          command: 'push'
          packagesToPush: '$(System.ArtifactsDirectory)/drop/*.nupkg;!$(System.ArtifactsDirectory)/drop/*.symbols.nupkg'
          nuGetFeedType: 'external'
          publishFeedCredentials: 'ASOS nuget.org feed'

